resolve parse error w/JSON
SyntaxError: Unexpected end of JSON input

resolved using stringify instead of parse, as it was unable to process all of the file data. console errors no longer being emitted w/stringify method